#define NOT_AVAILABLE 0
#define OUTPUT 1
#define INPUT_PULLUP 2
#define INPUT_PULLDOWN 3

/* PortA Pin States */
#define PORTA_PIN0 NOT_AVAILABLE
#define PORTA_PIN1 NOT_AVAILABLE
#define PORTA_PIN2 NOT_AVAILABLE
#define PORTA_PIN3 NOT_AVAILABLE
#define PORTA_PIN4 NOT_AVAILABLE
#define PORTA_PIN5 NOT_AVAILABLE
#define PORTA_PIN6 NOT_AVAILABLE
#define PORTA_PIN7 NOT_AVAILABLE

/* PortB Pin States */
#define PORTB_PIN0 NOT_AVAILABLE
#define PORTB_PIN1 NOT_AVAILABLE
#define PORTB_PIN2 NOT_AVAILABLE
#define PORTB_PIN3 NOT_AVAILABLE
#define PORTB_PIN4 NOT_AVAILABLE
#define PORTB_PIN5 NOT_AVAILABLE
#define PORTB_PIN6 NOT_AVAILABLE
#define PORTB_PIN7 NOT_AVAILABLE

/* PortC Pin States */
#define PORTC_PIN0 NOT_AVAILABLE
#define PORTC_PIN1 NOT_AVAILABLE
#define PORTC_PIN2 NOT_AVAILABLE
#define PORTC_PIN3 NOT_AVAILABLE
#define PORTC_PIN4 NOT_AVAILABLE
#define PORTC_PIN5 NOT_AVAILABLE
#define PORTC_PIN6 NOT_AVAILABLE
#define PORTC_PIN7 NOT_AVAILABLE

/* PortD Pin States */
#define PORTD_PIN0 NOT_AVAILABLE
#define PORTD_PIN1 NOT_AVAILABLE
#define PORTD_PIN2 NOT_AVAILABLE
#define PORTD_PIN3 NOT_AVAILABLE
#define PORTD_PIN4 NOT_AVAILABLE
#define PORTD_PIN5 NOT_AVAILABLE
#define PORTD_PIN6 NOT_AVAILABLE
#define PORTD_PIN7 NOT_AVAILABLE
